#include <bits/stdc++.h>
using namespace std;
long long a, b, c, aa, bb, cc, k, ans = 1ll << 62;
int main() {
  cin >> a >> b >> c;
  if (a == 1 && b == 0 && c == 0) return cout << "0", 0;
  if (a == 0 && b == 1 && c == 0) return cout << "0", 0;
  if (a == 0 && b == 0 && c == 1) return cout << "0", 0;
  if (a == 1 && b == 1 && c == 0) return cout << "0", 0;
  if (a == 0 && b == 1 && c == 1) return cout << "0", 0;
  aa = a;
  bb = b;
  cc = c;
  aa -= 2;
  bb -= 1;
  cc -= 1;
  k = max(aa, max(bb, cc));
  ans = min(ans, k - aa + k - bb + k - cc);
  aa = a;
  bb = b;
  cc = c;
  aa -= 2;
  bb -= 2;
  cc -= 1;
  k = max(aa, max(bb, cc));
  ans = min(ans, k - aa + k - bb + k - cc);
  aa = a;
  bb = b;
  cc = c;
  aa -= 2;
  bb -= 2;
  cc -= 2;
  k = max(aa, max(bb, cc));
  ans = min(ans, k - aa + k - bb + k - cc);
  aa = a;
  bb = b;
  cc = c;
  aa -= 1;
  bb -= 1;
  cc -= 1;
  k = max(aa, max(bb, cc));
  ans = min(ans, k - aa + k - bb + k - cc);
  aa = a;
  bb = b;
  cc = c;
  aa -= 1;
  bb -= 2;
  cc -= 1;
  k = max(aa, max(bb, cc));
  ans = min(ans, k - aa + k - bb + k - cc);
  aa = a;
  bb = b;
  cc = c;
  aa -= 1;
  bb -= 2;
  cc -= 2;
  k = max(aa, max(bb, cc));
  ans = min(ans, k - aa + k - bb + k - cc);
  aa = a;
  bb = b;
  cc = c;
  aa -= 1;
  bb -= 0;
  cc -= 1;
  k = max(aa, max(bb, cc));
  ans = min(ans, k - aa + k - bb + k - cc);
  aa = a;
  bb = b;
  cc = c;
  aa -= 1;
  bb -= 1;
  cc -= 1;
  k = max(aa, max(bb, cc));
  ans = min(ans, k - aa + k - bb + k - cc);
  aa = a;
  bb = b;
  cc = c;
  aa -= 1;
  bb -= 1;
  cc -= 2;
  k = max(aa, max(bb, cc));
  ans = min(ans, k - aa + k - bb + k - cc);
  cout << ans;
  return 0;
}
