#include <bits/stdc++.h>
using namespace std;
long long n, m, i, j, k;
string s;
string a[501];
int main() {
  a[1] = "Washington";
  a[2] = "Adams";
  a[3] = "Jefferson";
  a[15] = "Buchanan";
  a[4] = "Madison";
  a[16] = "Lincoln";
  a[5] = "Monroe";
  a[17] = "Johnson";
  a[6] = "Adams";
  a[18] = "Grant";
  a[7] = "Jackson";
  a[19] = "Hayes";
  a[8] = "Van Buren";
  a[20] = "Garfield";
  a[9] = "Harrison";
  a[21] = "Arthur";
  a[10] = "Tyler";
  a[22] = "Cleveland";
  a[11] = "Polk";
  a[23] = "Harrison";
  a[12] = "Taylor";
  a[24] = "Cleveland";
  a[13] = "Fillmore";
  a[25] = "McKinley";
  a[14] = "Pierce";
  a[26] = "Roosevelt";
  a[27] = "Taft";
  a[36] = "Johnson";
  a[28] = "Wilson";
  a[37] = "Nixon";
  a[29] = "Harding";
  a[38] = "Ford";
  a[30] = "Coolidge";
  a[39] = "Carter";
  a[31] = "Hoover";
  a[40] = "Reagan";
  a[32] = "Roosevelt";
  a[41] = "Bush";
  a[33] = "Truman";
  a[42] = "Clinton";
  a[34] = "Eisenhower";
  a[35] = "Kennedy";
  cin >> m;
  cout << a[m] << endl;
}
