n=int(input())
k=int(input())
a=int(input())
b=int(input())

if(k==1):
    print(n*a)
    exit()
else:
    c=0
    while(True):
        if(k>n):
            c+=a*(n-1)
            print(int(c))
            exit()
        elif(n%k!=0):
            #print('a')
            r=n-(n//k)*k
            c+=r*a
            n-=r
        else:
            #print('b')
            d=n-n/k
            if(b>d*a):
                c+=d*a
                n-=d
            else:
                c+=b
                n/=k
        #print(c,n)
        if(n==1):
            print(int(c))
            exit()
            
