n=int(input())
a=list(map(int,input().split()))
count1=0
count2=0
for i in range(len(a)):
    if(a[i]>0):
        count1=count1+1
    elif(a[i]<0):
        count2=count2+1
if(n%2==0):
    temp=n//2
else:
    temp=(n//2)+1
if(count1>=temp):
    print(1)
elif(count2>=(n//2)+1):
    print(-1)
else:
    print(0)