n=int(input())
ar=list(map(int,input().split()))
flag=True
ar1=sorted(list(set(ar)))
if(len(ar1)>3):
        ans=-1
        flag1=False
elif(len(ar1)==1):
    ans=0
elif(len(ar1)==2):
    p=(sum(ar1)//2)
    if(sum(ar1)%2==0):
        ans=min(abs(ar1[0]-p),abs(ar1[1]-p))
    else:
        ans=abs(ar1[1]-ar1[0])
else:
    if(abs(ar1[0]-ar1[1])==abs(ar1[1]-ar1[2])):
        ans=abs(ar[0]-ar1[1])
    else:
        ans=-1
if(flag):
    print(ans)
else:
    print(-1)
        