# -*- coding: utf-8 -*-
"""Untitled65.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HehGGS1BBjFFa8lGYvpcobNMxGHw0JwN
"""

a,b,c,d,e=input().split()
a=int(a)
b=int(b)
c=int(c)
d=int(d)
e=int(e)
flag=0
if b==d:
  print('YES')
else:
  while b!=c and d!=e:
      b+=1
      d-=1
      if b==a+1:
        b=1
      if d==-1:
        d=a
      if b==d:
        flag=1
        break
  if flag==1:
    print('YES')
  else:
    print('NO')

5