# -*- coding: utf-8 -*-
"""Untitled34.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zvXxg5kGM8olaK4O84sWcR-IzNpQsz5k
"""

word=input()
lower=word.lower()
vowels=['a','e','i','o','u']
arr=''
for l in lower:
  if l not in vowels:
  
    arr=arr+'.'+l

print(arr)