n,m,r=map(int,input().split())
a=list(map(int,input().split()))
b=list(map(int,input().split()))
ans=r
mn=min(a)
mx=max(b)
temp=r
i=0
while(temp>mn):
	temp=temp-mn
	i+=1
	ans=max(ans,(temp+i*mx))
print(ans)