# -*- coding: utf-8 -*-
"""Untitled56.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K9zIFsLtcOLH7zehDUTwmMg_CXFRqu9H
"""

n=int(input())
c=n//4
d=n%4
str1=""
for i in range(0,c):
  str1=str1+"abcd"
if d==1:
  str1=str1+"a"
elif d==2:
  str1=str1+"ab"
else:
  str1=str1+"abc"
print(str1)

