s=[[]]*8
s[0]="jolteon"
s[1]="flareon"
s[2]="espeon"
s[3]="umbreon"
s[4]="leafeon"
s[5]="glaceon"
s[6]="sylveon"
s[7]="vaporeon"
n=int(input())
ch=input()
il=0
ss=0
p=[[]]*8
o=0
while(o<8):
    p[o]=0
    o+=1
if(n==7):
    while(il<7):
        ss=0
        while(ss<len(s[il])):
            if(ch[ss]==s[il][ss]and n==len(s[il])):
                p[il]+=1
            ss+=1
        il+=1
    i=0
    ii=0
    while(i<8):
        if(p[i]==max(p)):
            ii=i
        i+=1
    print(s[ii])
else:
    if(n==5):
        print("espeon")
    else:
        print("vaporeon")
