def main():
    t=int(input())
    while(t>0):
        a,b=map(int,input().split())
        k=abs(a-b)
        cnt=0
        while(k!=0):
            if(k>=5):
                cnt=k//5
                k=k%5
            elif(k>=2):
                cnt=k//2
                k=k%2
            elif(k==1):
                cnt=cnt+1
                k=0
        print(cnt)
        t-=1
main()