n=int(input())
ro=int(input())
re=int(input())
oe=int(input())
count=1
temp=1
sum=0
while(count<n):
    if(temp==1):
        if(ro<re):
            temp=2
            sum=sum+ro
        else:
            temp=3
            sum=sum+re
    elif(temp==2):
        if(re<oe):
            temp=1
            sum=sum+re
        else:
            temp=3
            sum=sum+oe
    elif(temp==3):
        if(ro<oe):
            temp=1
            sum=sum+ro
        else:
            temp=2
            sum=sum+oe
    count=count+1
print(sum)