# -*- coding: utf-8 -*-
"""Untitled49.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sSZyuxen7-HP8V_27P5smUUORxrd3pZO
"""

for _ in range(int(input())):
  n=int(input())
  flag=0
  count=0
  a=2
  if n<2:
    print(0)
  else:   
      while n>a:
        num=2
        i=0
        while num<n:
          k=num
          num=2+3*i
          i+=1
        n=n-k
        count+=1
      print(count)

