n=int(input())
l=list(map(int,input().strip().split()))
val=[]
ans=[]
i=0
j=n-1
x=min(l[0],l[-1])
val.append(x)
if(x==l[0]):
    ans.append('L')
    i=1
else:
    ans.append('R')
    j-=1
while(True):
    if(i>=n or j<=0):
        break
    if(min(l[i],l[j])>x):
        x=min(l[i],l[j])
    elif(max(l[i],l[j])>x):
        x=max(l[i],l[j])
    else:
        break
    if(x==l[i]):
        val.append(l[i])
        ans.append('L')
        i+=1
    else:
        ans.append('R')
        val.append(l[j])
        j-=1
    if(i>j):
        break
print(len(ans))
print("".join(ans))