#include <bits/stdc++.h>
int main() {
  int a;
  scanf("%d", &a);
  a++;
  if (a == 2) printf("Washington");
  if (a == 3) printf("Adams");
  if (a == 4) printf("Jefferson");
  if (a == 5) printf("Madison");
  if (a == 6) printf("Monroe");
  if (a == 7) printf("Adams");
  if (a == 8) printf("Jackson");
  if (a == 9) printf("Van Buren");
  if (a == 10) printf("Hamison");
  if (a == 11) printf("Tyler");
  if (a == 12) printf("Polk");
  if (a == 13) printf("Taylor");
  if (a == 14) printf("Fillmore");
  if (a == 15) printf("Pierce");
  if (a == 16) printf("Buchanan");
  if (a == 17) printf("Lincoln");
  if (a == 18) printf("Johnson");
  if (a == 19) printf("Grant");
  if (a == 20) printf("Hayes");
  if (a == 21) printf("Garfield");
  if (a == 22) printf("Arthur");
  if (a == 23) printf("Cleveland");
  if (a == 24) printf("Hamison");
  if (a == 25) printf("Cleveland");
  if (a == 26) printf("McKinley");
  if (a == 27) printf("Roosevelt");
  if (a == 28) printf("Taft");
  if (a == 29) printf("Wilson");
  if (a == 30) printf("Harding");
  if (a == 31) printf("Coolidge");
  if (a == 32) printf("Hoover");
  if (a == 33) printf("Roosevelt");
  if (a == 34) printf("Truman");
  if (a == 35) printf("Eisenhower");
  if (a == 36) printf("Kennedy");
  if (a == 37) printf("Johnson");
  if (a == 38) printf("Nixon");
  if (a == 39) printf("Ford");
  if (a == 40) printf("Carfer");
  if (a == 41) printf("Reagen");
  return 0;
}
