# -*- coding: utf-8 -*-
"""testing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-zu9n5yozHvUdcS6FdEOJkpqYiHKXoiC
"""

n = int(input())
str1 = input()
sum = 0
for i in range(n):
  if eval(str1[i])%2 ==0:
    sum = sum + int(i) + 1
print(sum)