n,m,k=map(int,input().split())
l=list(map(int,input().split()))
y=max(l)
l.remove(y)
z=max(l)
a=m%(k+1)
if(a==0):
	h=m//(k+1)
	print((y*k+z)*h)
else:
	r=m//(k+1)
	l=(k+1)*r
	o=(m-l)*z
	print((y*k+z)*r+(m%(k+1))*y)