n,a,b,c=int(input()),int(input()),int(input()),int(input())
plas=a
glas=b-c
if(plas<=glas):
    print(int(n//plas))
else:
    if(n>=b):
        k=int((n-b)//(b-c))+1
        n-=((b-c)*k)
        if(n>=0):
            print(k+int(n//plas))
        else:
            print(k)
    else:
        print(int(n//plas))