s=input()
a=int(input())
min=int(s[3:])
hr=(a+min)//60
min=(a+min)%60
hr=hr+int(s[0:2])
if(hr>=24):
    hr=hr%24
if(hr<=9):
    hr='0'+str(hr)
if(min<=9):
    min='0'+str(min)
print(str(hr)+":"+str(min))
