s=input().strip()
l=s.split('+')
m=l[1].split('=')
a=len(l[0])
b=len(m[0])
c=len(m[1])
if(a+b==c):
    print(s)
elif(a+b-c==2):
    if(a>b):
        a-=1
    else:
        b-=1
    c+=1
    print('|'*a+'+'+'|'*b+'='+'|'*c)
elif(c-a-b==2):
    c-=1
    a+=1
    print('|'*a+'+'+'|'*b+'='+'|'*c)
else:
    print('Impossible')
