n, m = list(map(int,input().split()))
a = list(map(int,input().split()))
b = list(map(int,input().split()))
a.sort()
b.sort()
max1 = max(a[0]*b[0],a[0]*b[-1])
max2 = max(a[-1]*b[-1],a[-1]*b[0])
if max1 > max2:
    a.pop(0)
else:
    a.pop()
#print(a,b)
max1 = max(a[0]*b[0],a[0]*b[-1])
max2 = max(a[-1]*b[-1],a[-1]*b[0])
print(max(max1,max2))
