n,k=map(int,input().split())
y=input()
print(n)
check=y[:k]
check=check*(n//k)+check[:n%k]
if(check>=y):
 print(check)
else:
 carry=str(int(check[:k])+1)
 carry=carry*(n//k)+carry[:n%k]
 print(carry)
