q=int(input())
while q:
    n=int(input())
    if(n==4):print(1)
    elif(n==6):print(1)
    elif(n==8):print(2)
    elif(n==9):print(1)
    elif(n==10):print(2)
    elif(n==12):print(3)
    elif(n==13):print(2)
    elif(n==14):print(3)
    elif(n<14):print(-1)
    elif(n%2==0):
        if(n%4==0):print(n//4)
        else:print((n-6)//4+1)
    else:
        n-=9
        if(n%4==0):print(n//4+1)
        else:print((n-6)//4+1+1)
    q-=1    