n=int(input())
dict1={}
for i in range(n):
	a,b=map(str,input().split())
	b=''.join(sorted(b))
	a=int(a)
	try:
		dict1[b].append(a)
	except:
		KeyError
		dict1[b]=[a]
#print(dict1)
ans=10**19
if('ABC' in dict1.keys()):
	ans=min(ans,min(dict1['ABC']))
if('A' in dict1.keys() and 'B' in dict1.keys() and 'C' in dict1.keys()):
	ans=min(ans,min(dict1['A'])+min(dict1['B'])+min(dict1['C']))
try:
	ans=min(ans,min(dict1['AB'])+min(dict1['BC']))
except:
	KeyError
try:
	ans=min(ans,min(dict1['AB'])+min(dict1['C']))
except:
	KeyError
try:	
	ans=min(ans,min(dict1['AB'])+min(dict1['AC']))
except:
	KeyError
try:	
	ans=min(ans,min(dict1['AC'])+min(dict1['B']))
except:
	KeyError
try:
	ans=min(ans,min(dict1['AC'])+min(dict1['BC']))
except:
	KeyError
try:	
	ans=min(ans,min(dict1['BC'])+min(dict1['A']))
	#ans=min(ans,min(dict1['BC'])+min(dict1['BC']))
except:
	KeyError
if(ans==10**19):
	print(-1)
else:
	print(ans)
