l=[0]*26
n=int(input())
pres=[0]*26
s=input()
res=[0]*n
ii=-1
for i in s:
    ii+=1
    ind=ord(i)-ord('a')
    lol=0
    #print(ind)
    for j in range(ind+1,26):
        if(pres[j]!=0):
            lol=1
            if(l[j]==1):
                lol=2
                break
    if(lol==2):
        break
    pres[ind]=1
    if(lol==1):
        l[ind]=1
        res[ii]=1
    #print("lol")
#print(l)
#print(pres)
if(lol==2):
    print("NO")
else:
    print("YES")
    print(*res,sep="")