# -*- coding: utf-8 -*-
"""Untitled107.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u6_W-lgDcxo6VQcbAErlpni4iFbqFpzY
"""

for _ in range(int(input())):
  a,b=input().split()
  a=int(a)
  b=int(b)
  l=[]
  for i in range(a):
    k=list(input())
    l.append(k)
  count=0
  count+=l[-1].count('D')
  for i in l:
    if i[-1]=='R':
      count+=1
  print(count)

