n=(int)(input())
ll=list(map(int, input().split()))
l=list(set(ll))
c=0
l.sort()
if(len(l)>3):
    c=-1
else:
    if(len(l)==1):
        c=0
    elif(len(l)==2):
        if(abs(l[0]-l[1])%2==0):
            c=abs(l[0]-l[1])/2
        else:
            c=abs(l[0]-l[1])
    else:
        if(abs(l[2]-l[1])==abs(l[1]-l[0])):
            c=abs(l[2]-l[1])
        else:
            c=-1
print((int)(c))