n,m,r=map(int,input().split())
arr=list(map(int,input().split()))
arrb=list(map(int,input().split()))
arr.sort()
arrb.sort()
if(arr[0]>=arrb[m-1]):
    print(r)
else:
    buy=r//arr[0]
    r=r-(buy*arr[0])
    r=r+(buy*(arrb[m-1]))
    print(r)
