# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YJXlpE-tdxluyBiM0PtODA3gu43Bbpl0
"""

x = int(input())
kolvo = 0
for y in range(int(x/2)):
  if x % (y+1) == 0:
    kolvo +=1
print (kolvo)

