n=int(input())
if(n<=20):
    if(n==0):
        print("zero")
    if(n==1):
        print("one")
    if(n==2):
        print("two")
    if(n==3):
        print("three")
    if(n==4):
        print("four")
    if(n==5):
        print("five")
    if(n==6):
        print("six")
    if(n==7):
        print("seven")
    if(n==8):
        print("eight")
    if(n==9):
        print("nine")
    if(n==10):
        print("ten")
    if(n==11):
        print("eleven")
    if(n==12):
        print("twelve")
    if(n==13):
        print("thirteen")
    if(n==14):
        print("fourteen")
    if(n==15):
        print("fifteen")
    if(n==16):
        print("sixteen")
    if(n==17):
        print("seventeen")
    if(n==18):
        print("eighteen")
    if(n==19):
        print("nineteen")
    if(n==20):
        print("twenty")

ar1=["","one","two","three","four","five","six","seven","eight","nine"]
ar2=["twenty","thirty","forty","fifty","sixty","seventy","eighty","ninety"]
if(n>20):
    c=n%10
    d=n//10
    if(c==0):
        print(ar2[d-2])
    else:
        s=ar2[d-2]+"-"+ar1[c]
        print(s)
    
    
