T=int(input())
while(T):
    n,k=map(int,input().split()) 
    c=0
    while(n):
        if((n%k)!=0):
            c=c+(n%k) 
            n=n-(n%k) 
        else:
            n=n//k
            c=c+1
    c=int(c) 
    print(c)
    T=T-1