A=["AKIHABARA","KIHBR", "AKIHBR", "KIHABR", "KIHBAR", "KIHBRA","AKIHABR","AKIHBAR","AKIHBRA","KIHABAR","KIHABRA","KIHBARA","AKIHABAR","AKIHABRA","AKIHBARA","KIHABARA"]
S=input()
if S in A:
  print("YES")
else:
  print("NO")

