# -*- coding: utf-8 -*-
"""Untitled47.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OgNIJPShWiz2fqqh6gz4uFwE2iIxebkJ
"""

m,n=map(int,input().split())
l1=[]
for i in range(0,m):
  l2=[]
  for j in range(0,n):
    if i==0 or i%2==0:
      l2.append("#")
    else:
      l2.append(".")
  l1.append(l2)
for i in range(1,m,4):
  l1[i][n-1]="#"
for i in range(3,m,4):
  l1[i][0]="#"
for x in l1:
  for y in x:
    print(y,end="")
  print()