n,m,k=map(int,input().split())
l=list(map(int,input().split()))
l.sort(reverse=True)
if(m<k):
    print("0")
else:
    c=k
    i=0
    j=0
    flag=0
    while(c<m):
        if(i==n):
            flag=1
            break
        c=c-1
        c=c+l[i]
        i=i+1
        j=j+1
    if(flag==1):
        print("-1")
    else:
        print(j)