n,x,y=map(int,input().split())
a=list(map(int,input().split()))
i=0
if(y==0):
    print(1)
else:
    while(i<n):
        if(i<n-1):
            if(a[i+1]<a[i]):
                i+=1
        if(min(a[i:min(n,i+y+1)])==a[i]):
            print(i+1)
            break
        i+=1